<?php

namespace Nirvona\Repositories;

/**
 * LeaderboardRepository
 *
 * Data Access Layer for Leaderboard model (precomputed ranking
 * snapshots). Snapshot rows are regenerated by a scoring job - this
 * repository reads them and replaces a scope's rows wholesale.
 */
class LeaderboardRepository extends BaseRepository
{
    protected string $table = 'leaderboards';

    /**
     * Get the leaderboard for one exam
     *
     * @param string $examId
     * @param int $limit
     * @return array
     */
    public function getByExam(string $examId, int $limit = 100): array
    {
        return $this->select(
            "SELECT * FROM {$this->table} WHERE examId = ? ORDER BY rank ASC LIMIT ?",
            [$examId, $limit]
        );
    }

    /**
     * Get a course-level leaderboard for a given period
     *
     * @param string $courseSlug
     * @param string $period "weekly" | "monthly" | "all-time"
     * @param int $limit
     * @return array
     */
    public function getByCourse(string $courseSlug, string $period = 'all-time', int $limit = 100): array
    {
        return $this->select(
            "SELECT * FROM {$this->table}
             WHERE courseSlug = ? AND period = ?
             ORDER BY rank ASC
             LIMIT ?",
            [$courseSlug, $period, $limit]
        );
    }

    /**
     * Get a single student's rank entry for an exam
     *
     * @param string $examId
     * @param string $studentId
     * @return ?array
     */
    public function getStudentRank(string $examId, string $studentId): ?array
    {
        return $this->selectOne(
            "SELECT * FROM {$this->table} WHERE examId = ? AND studentId = ? LIMIT 1",
            [$examId, $studentId]
        );
    }

    /**
     * Replace all leaderboard rows for an exam with a freshly computed set.
     * Used by the scoring job after results are published.
     *
     * @param string $examId
     * @param array $rows Each row must include studentId, rank, score, percentage, ...
     * @return int Number of rows inserted
     */
    public function replaceForExam(string $examId, array $rows): int
    {
        $this->db->prepare("DELETE FROM {$this->table} WHERE examId = ?")->execute([$examId]);

        $inserted = 0;
        foreach ($rows as $row) {
            $row['examId'] = $examId;
            $row['period'] = $row['period'] ?? 'exam';
            $this->create($row);
            $inserted++;
        }

        return $inserted;
    }
}
