<?php

/**
 * Migration: Create Leaderboards Table
 *
 * Precomputed leaderboard snapshots (per exam, per course, or an
 * all-time cohort) so ranking pages don't recompute rank/percentile
 * across the full results table on every request. `period` selects the
 * snapshot scope: 'exam' | 'weekly' | 'monthly' | 'all-time'.
 * Regenerated by a background job whenever results are published;
 * StudentRepository::getLeaderboard() / ResultRepository::getLeaderboard()
 * can be pointed at this table once that job exists, instead of
 * aggregating live.
 *
 * `rank` is backtick-quoted (reserved word in MySQL 8.0.2+, same as
 * results.rank).
 */
return [
    'up' => function (\PDO $pdo) {
        $sql = "
            CREATE TABLE IF NOT EXISTS leaderboards (
                id CHAR(36) PRIMARY KEY,
                examId CHAR(36),
                courseSlug VARCHAR(50),
                studentId CHAR(36) NOT NULL,
                studentName VARCHAR(255),
                className VARCHAR(100),
                `rank` INT NOT NULL,
                score DECIMAL(10, 2),
                percentage DECIMAL(5, 2),
                avgPercentage DECIMAL(5, 2),
                totalExams INT DEFAULT 0,
                bestRank INT,
                period VARCHAR(20) DEFAULT 'exam',
                generatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_leaderboards_exam FOREIGN KEY (examId) REFERENCES exams(id) ON DELETE CASCADE,
                CONSTRAINT fk_leaderboards_course FOREIGN KEY (courseSlug) REFERENCES courses(slug) ON DELETE CASCADE,
                CONSTRAINT fk_leaderboards_student FOREIGN KEY (studentId) REFERENCES students(id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

            CREATE INDEX idx_leaderboards_examId ON leaderboards(examId);
            CREATE INDEX idx_leaderboards_courseSlug ON leaderboards(courseSlug);
            CREATE INDEX idx_leaderboards_rank ON leaderboards(`rank`);
            CREATE INDEX idx_leaderboards_period ON leaderboards(period);
        ";

        $pdo->exec($sql);
    },

    'down' => function (\PDO $pdo) {
        $pdo->exec("DROP TABLE IF EXISTS leaderboards;");
    },
];
