<?php

/**
 * Migration: Create Leaderboards Table
 *
 * Precomputed leaderboard snapshots (per exam, per course, or an
 * all-time cohort) so ranking pages don't recompute rank/percentile
 * across the full results table on every request. `period` selects the
 * snapshot scope: 'exam' | 'weekly' | 'monthly' | 'all-time'.
 * Regenerated by a background job whenever results are published;
 * StudentRepository::getLeaderboard() / ResultRepository::getLeaderboard()
 * can be pointed at this table once that job exists, instead of
 * aggregating live.
 */
return [
    'up' => function (\PDO $pdo) {
        $sql = "
            CREATE TABLE IF NOT EXISTS leaderboards (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                examId UUID REFERENCES exams(id) ON DELETE CASCADE,
                courseSlug VARCHAR(50) REFERENCES courses(slug) ON DELETE CASCADE,
                studentId UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
                studentName VARCHAR(255),
                className VARCHAR(100),
                rank INT NOT NULL,
                score DECIMAL(10, 2),
                percentage DECIMAL(5, 2),
                avgPercentage DECIMAL(5, 2),
                totalExams INT DEFAULT 0,
                bestRank INT,
                period VARCHAR(20) DEFAULT 'exam',
                generatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX idx_leaderboards_examId ON leaderboards(examId);
            CREATE INDEX idx_leaderboards_courseSlug ON leaderboards(courseSlug);
            CREATE INDEX idx_leaderboards_rank ON leaderboards(rank);
            CREATE INDEX idx_leaderboards_period ON leaderboards(period);
        ";

        $pdo->exec($sql);
    },

    'down' => function (\PDO $pdo) {
        $pdo->exec("DROP TABLE IF EXISTS leaderboards CASCADE;");
    },
];
